version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/node:23.8.0

jobs:
  setup:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install tools & lint & test
          command: |
            pwd
  unit_test_1:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install tools & lint & test 1
          command: |
            pwd
  unit_test_2:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install tools & lint & test 2
          command: |
            pwd

  build_and_deploy:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/ng build --aot --output-hashing=all --base-href='https://khiencct.web.app/';
            fi
      - run:
          name: Deploy to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $GOOGLE_APPLICATION_CREDENTIALS > credentials.json
              GOOGLE_APPLICATION_CREDENTIALS=credentials.json ./node_modules/.bin/firebase deploy --project khiencct;
            fi
          filters:
            branches:
              only:
                - dev
                - master
workflows:
  workflow:
    jobs:
      - setup
      - unit_test_1:
          requires:
            - setup
      - unit_test_2:
          requires:
            - setup
      - build_and_deploy:
          requires:
            - unit_test_1
