version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/node:23.8.0

jobs:
  setup:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: mkdir -p /workspace && echo "Hello CircleCI" > /workspace/message.txt
      - persist_to_workspace:
          root: ~/angular_circleci
          paths:
            - message.txt
      - run:
          name: Install tools & lint
          command: |
            pwd
  unit_test:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit test
          command: |
            pwd
  integration_test:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Integration test
          command: |
            pwd

  functional_test:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Functional test
          command: |
            pwd

  build_and_deploy:
    working_directory: ~/angular_circleci
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/angular_circleci
      - run:
          name: Build project
          command: |
            pwd
            ls -la
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/ng build --aot --output-hashing=all --base-href='https://khiencct.web.app/';
            fi
      - run:
          name: Deploy to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $GOOGLE_APPLICATION_CREDENTIALS > credentials.json
              GOOGLE_APPLICATION_CREDENTIALS=credentials.json ./node_modules/.bin/firebase deploy --project khiencct;
            fi
          filters:
            branches:
              only:
                - dev
                - master
workflows:
  workflow:
    jobs:
      - setup
      - unit_test:
          requires:
            - setup
      - integration_test:
          requires:
            - setup
      - functional_test:
          requires:
            - setup
      - build_and_deploy:
          requires:
            - unit_test
            - integration_test
            - functional_test
